---
title: "HW Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We'll use one of the provided datasets.

```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("rest_inspec")

inspec = 
  rest_inspec %>% 
  select(boro, building, critical_flag, cuisine_description, grade, score, inspection_date) %>%
  filter(
    !is.na(grade),
    grade != "Not Yet Graded",
    grade != "Z",
    grade != "P",
    boro == c("BROOKLYN", "QUEENS", "BRONX", "MANHATTAN"),
    cuisine_description == c("Italian", "American", "Chinese", "Korean"),
    score %in% 0:30
  )
```



## Scatterplot
Here's a scatter plot 
```{r}
inspec %>% 
  mutate(text_label = str_c("Grade: ", grade, "\nSeverity: ", critical_flag)) %>% 
  plot_ly(
    x = ~inspection_date, 
    y = ~score, 
    type = "scatter", 
    mode = "markers",
    color = ~cuisine_description, 
    text = ~text_label, 
    alpha = 0.5)
```

## Boxplot
Here's a box plot 

```{r}
inspec %>% 
  plot_ly(
    x = ~boro, 
    y = ~score,
    type = "box"
  )
```


